import type { Database } from '@core/db/database.types'

import type {
  ChiefComplaint,
  DoctorReference,
  DurationUnit,
  Visit,
  VisitAdvice,
  VitalsReading,
} from './visit.types'

const DURATION_UNITS: readonly DurationUnit[] = ['DAYS', 'WEEKS', 'MONTHS', 'YEARS']

/**
 * The stored complaint list, read defensively: it is jsonb, so an entry
 * without a complaint is dropped and a malformed duration reads as absent
 * rather than as a number nobody wrote.
 */
export function toChiefComplaints(value: unknown): ChiefComplaint[] {
  if (!Array.isArray(value)) return []
  return value.flatMap((item): ChiefComplaint[] => {
    if (typeof item !== 'object' || item === null) return []
    const entry = item as Record<string, unknown>
    const complaint = typeof entry.complaint === 'string' ? entry.complaint.trim() : ''
    if (!complaint) return []
    const n = entry.durationValue
    const unit = entry.durationUnit
    const durationValue = typeof n === 'number' && Number.isFinite(n) && n > 0 ? n : null
    const durationUnit =
      durationValue !== null && typeof unit === 'string' && (DURATION_UNITS as readonly string[]).includes(unit)
        ? (unit as DurationUnit)
        : null
    return [{ complaint, durationValue: durationUnit ? durationValue : null, durationUnit }]
  })
}

/**
 * Visit rows, and how they become domain objects.
 *
 * Separated from the repository so it can be tested without a database. The
 * decision that earns this file is the blood-pressure pairing: two nullable
 * columns become one nullable object, so a lone diastolic — which is not a
 * blood pressure — cannot reach a renderer.
 *
 * Row shapes come from `database.types.ts`, generated by `pnpm db:types`.
 */

type Tables = Database['public']['Tables']

/** `visits` — see supabase/migrations/0005_visits.sql. */
export type VisitRow = Tables['visits']['Row']

/** `visit_vitals` — one row per reading, never one row per visit. */
export type VisitVitalsRow = Tables['visit_vitals']['Row']

/** `visit_advice` — at most one row per visit, written by the atomic save. */
export type VisitAdviceRow = Tables['visit_advice']['Row']

/** `doctor_references` — see supabase/migrations/0024_cockpit_clinical_history.sql. */
export type DoctorReferenceRow = Tables['doctor_references']['Row']

/* -------------------------------------------------------------------------- */
/* Mapping                                                                    */
/* -------------------------------------------------------------------------- */

export function toVisit(row: VisitRow): Visit {
  return {
    id: row.id,
    clinicId: row.clinic_id,
    patientId: row.patient_id,
    pregnancyId: row.pregnancy_id,
    visitType: row.visit_type,
    status: row.status,
    occurredAt: row.occurred_at,
    // Null while open. The cockpit then computes gestational age live from the
    // pregnancy's anchor rather than showing a value captured at check-in.
    gaDaysAtVisit: row.ga_days_at_visit,
    datingMethodAtVisit: row.dating_method_at_visit,
    impression: row.impression,
    examination: row.examination,
    systemicExamination: {
      perAbdomen: row.exam_per_abdomen,
      perVaginum: row.exam_per_vaginum,
      perSpeculum: row.exam_per_speculum,
    },
    chiefComplaints: toChiefComplaints(row.chief_complaints),
    diagnosis: row.diagnosis,
    consultationSummary: row.consultation_summary,
    clinicianId: row.clinician_id,
    openedBy: row.opened_by,
    closure: {
      savedAt: row.saved_at,
      savedBy: row.saved_by,
      cancelledAt: row.cancelled_at,
      cancelledBy: row.cancelled_by,
      cancellationReason: row.cancellation_reason,
    },
    version: row.version,
  }
}

export function toVitalsReading(row: VisitVitalsRow): VitalsReading {
  return {
    id: row.id,
    sequenceNo: row.sequence_no,
    // `visit_vitals_bp_paired` makes these two columns rise and fall together,
    // so the partial case is unreachable. Requiring both here means a lone
    // diastolic could never be rendered as though it were a reading.
    bloodPressure:
      row.bp_systolic_mmhg !== null && row.bp_diastolic_mmhg !== null
        ? { systolicMmHg: row.bp_systolic_mmhg, diastolicMmHg: row.bp_diastolic_mmhg }
        : null,
    pulseBpm: row.pulse_bpm,
    respiratoryRateBpm: row.respiratory_rate_bpm,
    // Postgres numeric can arrive as a string through PostgREST. These are
    // temperatures, weights and fundal heights — well inside what a JS number
    // holds exactly — but parsing explicitly keeps a string out of code that
    // expects to do arithmetic or call toFixed on it.
    temperatureC: toNumber(row.temperature_c),
    spo2Percent: row.spo2_percent,
    weightKg: toNumber(row.weight_kg),
    fundalHeightCm: toNumber(row.fundal_height_cm),
    fetalHeartRateBpm: row.fetal_heart_rate_bpm,
    // NIL is a recorded negative result; null is "not tested". Preserved as
    // distinct, because a chart that shows nothing for an untested field must
    // not read as a negative one (ARCH-10).
    urineAlbumin: row.urine_albumin,
    urineSugar: row.urine_sugar,
    note: row.note,
    recordedAt: row.recorded_at,
    recordedBy: row.recorded_by,
  }
}

export function toVisitAdvice(row: VisitAdviceRow): VisitAdvice {
  return {
    id: row.id,
    visitId: row.visit_id,
    dfkcCounselled: row.dfkc_counselled,
    nutritionCounselled: row.nutrition_counselled,
    leftLateralRest: row.left_lateral_rest,
    dangerSignsCounselled: row.danger_signs_counselled,
    // `text[] not null default '{}'` — an empty array is "nothing was ordered",
    // which is a different statement from "no advice record exists", and only
    // the caller that found no row at all may say the second one.
    labOrders: row.lab_orders,
    scanOrders: row.scan_orders,
    nextFollowupDate: row.next_followup_date,
    additionalAdvice: row.additional_advice,
    recordedBy: row.recorded_by,
  }
}

/**
 * A reference row, with the colleague's name resolved by the caller.
 *
 * `doctor_references_has_recipient` guarantees one of the two recipient
 * columns is present; the external branch is used only when no colleague is
 * named.
 */
export function toDoctorReference(
  row: DoctorReferenceRow,
  colleagueNames: ReadonlyMap<string, string>,
): DoctorReference {
  return {
    id: row.id,
    visitId: row.visit_id,
    recipient: row.to_staff_user_id
      ? {
          kind: 'COLLEAGUE',
          staffUserId: row.to_staff_user_id,
          displayName: colleagueNames.get(row.to_staff_user_id) ?? null,
        }
      : { kind: 'EXTERNAL', name: row.to_external_name ?? '' },
    specialty: row.to_specialty,
    facility: row.to_facility,
    reason: row.reason,
    urgency: row.urgency === 'URGENT' ? 'URGENT' : 'ROUTINE',
    createdAt: row.created_at,
  }
}

function toNumber(value: number | string | null): number | null {
  if (value === null) return null
  const parsed = typeof value === 'number' ? value : Number(value)
  return Number.isFinite(parsed) ? parsed : null
}
