import 'server-only'

import { createServerClient } from '@supabase/ssr'
import { createClient, type SupabaseClient } from '@supabase/supabase-js'
import { cookies } from 'next/headers'

import { publicEnv, serverEnv } from '@core/config/env'

import type { Database } from './database.types'

/**
 * Database clients, in exactly two flavours, with different trust levels.
 *
 * ---------------------------------------------------------------------------
 * 1. `userClient()` — acts AS the signed-in staff member
 * ---------------------------------------------------------------------------
 * Carries their session, so every query is filtered by the RLS policies in
 * migration 0012. This is the default for reads. If a query returns a row, the
 * database has already confirmed the caller is a member of that clinic.
 *
 * ---------------------------------------------------------------------------
 * 2. `serviceClient()` — BYPASSES all row level security
 * ---------------------------------------------------------------------------
 * Needed for three things RLS cannot express: multi-table atomic commits, the
 * public referral page (no session exists), and worker jobs.
 *
 * Every caller must perform its own explicit authorization first (ARCH-5).
 * There is no safety net behind this client — it is the safety net.
 *
 * `import 'server-only'` above makes importing this file from a client
 * component a build error, so the service-role key cannot reach a browser
 * bundle by accident.
 */

/**
 * A Supabase client that knows this database's schema.
 *
 * Generated by `pnpm db:types`. Passing `Database` here is what makes a typo in
 * a column name, or a filter on a column that does not exist, a compile error
 * rather than an empty result set at the counter.
 */
export type TypedClient = SupabaseClient<Database>

/** Acts as the signed-in user. Subject to RLS. Use this for reads. */
export async function userClient(): Promise<TypedClient> {
  const cookieStore = await cookies()

  return createServerClient<Database>(publicEnv.NEXT_PUBLIC_SUPABASE_URL, publicEnv.NEXT_PUBLIC_SUPABASE_ANON_KEY, {
    cookies: {
      getAll() {
        return cookieStore.getAll()
      },
      setAll(cookiesToSet) {
        try {
          for (const { name, value, options } of cookiesToSet) {
            cookieStore.set(name, value, options)
          }
        } catch {
          // Called from a Server Component, where cookies are read-only. Session
          // refresh is handled by middleware, so this is safe to ignore.
        }
      },
    },
  })
}

let cachedServiceClient: TypedClient | null = null

/**
 * Bypasses RLS entirely. The caller is responsible for authorization.
 *
 * Reach for `userClient()` first. Use this only when one of the three cases in
 * the file header genuinely applies, and say which one in a comment at the call
 * site.
 */
export function serviceClient(): TypedClient {
  if (cachedServiceClient) return cachedServiceClient

  const env = serverEnv()

  cachedServiceClient = createClient<Database>(
    publicEnv.NEXT_PUBLIC_SUPABASE_URL,
    env.SUPABASE_SERVICE_ROLE_KEY,
    {
      auth: {
        // A service client has no user and must never pick one up from storage
        // or silently refresh someone else's session.
        autoRefreshToken: false,
        persistSession: false,
        detectSessionInUrl: false,
      },
    },
  )

  return cachedServiceClient
}
