import type { Database } from '@core/db/database.types'
import { internal } from '@core/errors/app-error'

import { ReferralSnapshotSchema } from './referral.schema'
import type {
  Referral,
  ReferralDocument,
  ReferralDraftFields,
  ReferralLink,
  ReferralSnapshot,
  SnapshotExamination,
  SnapshotTransferVitals,
} from './referral.types'

/**
 * Referral rows, and how they become domain objects.
 *
 * Separated from the repository so the decisions in it are unit-testable
 * without a database, and there are three worth testing.
 *
 *   The status column plus a nullable snapshot become one discriminated union.
 *   A row claiming to be ISSUED with no snapshot is not a referral in a slightly
 *   odd state — it is a row that cannot be rendered, and it raises here rather
 *   than reaching a print view that would quietly show an empty page.
 *
 *   The frozen snapshot is PARSED, not cast. It is `jsonb`, so it arrives as
 *   `unknown` whatever wrote it; a document frozen by an older build must fail
 *   loudly here rather than render `undefined` in the middle of a dose (ARCH-6).
 *
 *   Transfer vitals and the vaginal examination collapse their nullable columns
 *   into the same tagged unions the snapshot uses, so the draft form and the
 *   issued slip are shaped identically and one component can render both.
 *
 * Row shapes come from `database.types.ts`, generated by `pnpm db:types`.
 */

type Tables = Database['public']['Tables']

/** `referrals` — see supabase/migrations/0010_referrals.sql. */
export type ReferralRow = Tables['referrals']['Row']

/** `referral_access_tokens`. The hash column is never mapped into the domain. */
export type ReferralAccessTokenRow = Tables['referral_access_tokens']['Row']

/* -------------------------------------------------------------------------- */
/* Mapping                                                                    */
/* -------------------------------------------------------------------------- */

export function toReferral(row: ReferralRow): Referral {
  return {
    id: row.id,
    clinicId: row.clinic_id,
    patientId: row.patient_id,
    pregnancyId: row.pregnancy_id,
    originVisitId: row.origin_visit_id,
    supersedesId: row.supersedes_id,
    document: toDocument(row),
    createdBy: row.created_by,
    createdAt: row.created_at,
    version: row.version,
  }
}

/**
 * The state of the referral, and only what that state makes available.
 *
 * The `referrals_issued_is_complete` CHECK in 0010 already guarantees that an
 * issued row carries a snapshot, an issuer and a timestamp. The throws below
 * are therefore unreachable through the database — which is exactly why they
 * throw rather than degrade: if one is ever hit, something has bypassed the
 * constraint, and a handover document is the last place to paper over that.
 */
function toDocument(row: ReferralRow): ReferralDocument {
  switch (row.status) {
    case 'DRAFT':
      return { state: 'DRAFT', draft: toDraftFields(row) }

    case 'CANCELLED':
      return {
        state: 'CANCELLED',
        cancelledAt: row.cancelled_at ?? row.updated_at,
        cancelledBy: row.cancelled_by,
        // The CHECK makes a cancellation without a reason impossible.
        reason: row.cancellation_reason ?? 'No reason recorded',
      }

    case 'ISSUED':
      return {
        state: 'ISSUED',
        snapshot: parseSnapshot(row),
        snapshotSchemaVersion: required(row, row.snapshot_schema_version, 'snapshot_schema_version'),
        issuedAt: required(row, row.issued_at, 'issued_at'),
        issuedBy: required(row, row.issued_by, 'issued_by'),
      }

    case 'SUPERSEDED':
      return {
        state: 'SUPERSEDED',
        snapshot: parseSnapshot(row),
        snapshotSchemaVersion: required(row, row.snapshot_schema_version, 'snapshot_schema_version'),
        issuedAt: required(row, row.issued_at, 'issued_at'),
        issuedBy: required(row, row.issued_by, 'issued_by'),
        supersededAt: required(row, row.superseded_at, 'superseded_at'),
      }
  }
}

function required<T>(row: ReferralRow, value: T | null, column: string): T {
  if (value === null) {
    throw internal(
      `Referral ${row.id} is ${row.status} but has no ${column}. It cannot be rendered as a handover document.`,
    )
  }
  return value
}

/**
 * The frozen document.
 *
 * Exported because the public page resolves a token to a snapshot without ever
 * loading a referral row, and must parse it the same way.
 */
export function parseSnapshot(row: Pick<ReferralRow, 'id' | 'issued_snapshot'>): ReferralSnapshot {
  return parseSnapshotJson(row.issued_snapshot, row.id)
}

export function parseSnapshotJson(value: unknown, referralId: string): ReferralSnapshot {
  if (value === null || value === undefined) {
    throw internal(`Referral ${referralId} has no frozen snapshot to render.`)
  }

  const parsed = ReferralSnapshotSchema.safeParse(value)
  if (!parsed.success) {
    throw internal(
      `Referral ${referralId} has a frozen snapshot this build cannot read. Refusing to render a partial handover document.`,
      parsed.error,
    )
  }

  return parsed.data as ReferralSnapshot
}

/**
 * A draft's editable fields.
 *
 * Vitals and the examination are folded into the same tagged unions used by the
 * snapshot. Their timestamp is what decides the tag: the routine in 0021 clears
 * it whenever nothing was measured, so a row with a time has readings and a row
 * without has none — which is the invariant that stops a blank BP rendering as
 * a reading that was taken and found unremarkable.
 */
function toDraftFields(row: ReferralRow): ReferralDraftFields {
  return {
    referringFacility: row.referring_facility,
    referringDoctorName: row.referring_doctor_name,
    referringContactPhone: row.referring_contact_phone,
    receivingFacility: row.receiving_facility,
    receivingContact: row.receiving_contact,
    transportMode: row.transport_mode,
    departureAt: row.departure_at,
    indication: row.indication,
    clinicalSummary: row.clinical_summary,
    transferVitals: toTransferVitals(row),
    examination: toExamination(row),
    linesAndCatheters: row.lines_and_catheters,
    accompanyingStaff: row.accompanying_staff,
  }
}

function toTransferVitals(row: ReferralRow): SnapshotTransferVitals {
  if (row.transfer_vitals_recorded_at === null) return { status: 'NOT_RECORDED' }

  return {
    status: 'RECORDED',
    recordedAt: row.transfer_vitals_recorded_at,
    // Paired by the `referrals_bp_paired` CHECK, so the half-pair case is
    // unreachable. Requiring both here means a lone diastolic could never be
    // rendered as though it were a blood pressure.
    bloodPressure:
      row.transfer_bp_systolic_mmhg !== null && row.transfer_bp_diastolic_mmhg !== null
        ? {
            systolicMmHg: row.transfer_bp_systolic_mmhg,
            diastolicMmHg: row.transfer_bp_diastolic_mmhg,
          }
        : null,
    pulseBpm: row.transfer_pulse_bpm,
    respiratoryRateBpm: row.transfer_respiratory_rate_bpm,
    spo2Percent: row.transfer_spo2_percent,
    temperatureC: toNumber(row.transfer_temperature_c),
    urineAlbumin: row.transfer_urine_albumin,
    fetalHeartRateBpm: row.transfer_fetal_heart_rate_bpm,
  }
}

function toExamination(row: ReferralRow): SnapshotExamination {
  if (row.pv_examined_at === null) return { status: 'NOT_PERFORMED' }

  return {
    status: 'PERFORMED',
    examinedAt: row.pv_examined_at,
    // The draft form shows the examiner's id; the frozen snapshot resolves it
    // to a name. Only the snapshot travels, so only the snapshot needs one.
    examinedBy: row.pv_examined_by,
    dilatationCm: toNumber(row.pv_dilatation_cm),
    effacementPercent: row.pv_effacement_percent,
    station: row.pv_station,
    membranes: row.pv_membranes,
    liquor: row.pv_liquor,
  }
}

export function toReferralLink(row: ReferralAccessTokenRow): ReferralLink {
  return {
    id: row.id,
    expiresAt: row.expires_at,
    revokedAt: row.revoked_at,
    issuedBy: row.issued_by,
    createdAt: row.created_at,
  }
}

/**
 * Postgres `numeric` can arrive as a string through PostgREST.
 *
 * These are temperatures and cervical dilatations, well inside what a JS number
 * holds exactly, but parsing explicitly keeps a string out of code that expects
 * to call `toFixed` on it.
 */
function toNumber(value: number | string | null): number | null {
  if (value === null) return null
  const parsed = typeof value === 'number' ? value : Number(value)
  return Number.isFinite(parsed) ? parsed : null
}
