import type { Database } from '@core/db/database.types'
import { internal } from '@core/errors/app-error'

import type {
  BirthPlan,
  ObstetricHistoryEntry,
  Pregnancy,
  PregnancyDating,
} from './pregnancy.types'

/**
 * Pregnancy rows, and how they become domain objects.
 *
 * Separated from the repository so it can be tested without a database. The
 * decision that earns this file is `toDating`: the two anchor columns rise and
 * fall together, and collapsing a half-present anchor into a gestational age
 * would put a fabricated number on the cockpit badge.
 *
 * Row shapes come from `database.types.ts`, generated by `pnpm db:types`.
 */

type Tables = Database['public']['Tables']

/** `pregnancies` — see supabase/migrations/0004_pregnancies.sql. */
export type PregnancyRow = Tables['pregnancies']['Row']

/** `obstetric_history` — prior pregnancies, wherever they happened. */
export type ObstetricHistoryRow = Tables['obstetric_history']['Row']

/* -------------------------------------------------------------------------- */
/* Mapping                                                                    */
/* -------------------------------------------------------------------------- */

type DatingColumns = Pick<
  PregnancyRow,
  | 'dating_reference_date'
  | 'dating_reference_ga_days'
  | 'dating_method'
  | 'dating_certainty'
  | 'dating_confirmed_by'
  | 'dating_confirmed_at'
>

/**
 * Dating, or the explicit absence of it.
 *
 * `pregnancies_dating_reference_complete` makes the two anchor columns rise and
 * fall together, so exactly one of these branches is reachable. Both are
 * checked anyway: if a half-anchor ever did appear, treating it as established
 * would produce a gestational age computed from a null, and treating it as
 * absent would silently discard a real date. Neither is acceptable, so it
 * raises.
 */
export function toDating(row: DatingColumns): PregnancyDating {
  const hasDate = row.dating_reference_date !== null
  const hasGa = row.dating_reference_ga_days !== null

  if (!hasDate && !hasGa) return { status: 'NOT_ESTABLISHED' }

  if (!hasDate || !hasGa) {
    throw internal(
      'A pregnancy row carries half a dating anchor; gestational age cannot be derived from it.',
    )
  }

  // An anchored pregnancy whose method column still reads UNKNOWN is
  // contradictory. It is surfaced as a clinical estimate rather than discarded:
  // the anchor is real and a clinician put it there, but claiming it came from
  // an LMP or a scan would invent provenance it does not have.
  const method =
    row.dating_method === 'UNKNOWN' ? 'CLINICAL_ESTIMATE' : row.dating_method

  return {
    status: 'ESTABLISHED',
    reference: {
      referenceDate: row.dating_reference_date as string,
      referenceGaDays: row.dating_reference_ga_days as number,
    },
    method,
    certainty: row.dating_certainty,
    confirmedBy: row.dating_confirmed_by,
    confirmedAt: row.dating_confirmed_at,
  }
}

export function toObstetricHistoryEntry(row: ObstetricHistoryRow): ObstetricHistoryEntry {
  return {
    id: row.id,
    sequenceNo: row.sequence_no,
    yearOfEvent: row.year_of_event,
    eventDate: row.event_date,
    eventDatePrecision: row.event_date_precision,
    outcome: row.outcome,
    deliveryMode: row.delivery_mode,
    gestationWeeksAtDelivery: row.gestation_weeks_at_delivery,
    birthWeightGrams: row.birth_weight_grams,
    childAlive: row.child_alive,
    hasUterineScar: row.has_uterine_scar,
    scarIndication: row.scar_indication,
    complications: row.complications,
    placeOfEvent: row.place_of_event,
    source: row.source,
  }
}

export function toPregnancy(row: PregnancyRow): Pregnancy {
  return {
    id: row.id,
    clinicId: row.clinic_id,
    patientId: row.patient_id,
    status: row.status,
    dating: toDating(row),
    reportedLmp: {
      date: row.reported_lmp,
      certainty: row.reported_lmp_certainty,
    },
    // Each left null when not recorded. "Not asked" must not render as zero,
    // which on a G/P line would read as a first pregnancy.
    gravidaParity: {
      gravida: row.gravida,
      parity: row.parity,
      living: row.living,
      abortions: row.abortions,
    },
    // Postgres numeric arrives as a string through PostgREST when it exceeds
    // what a JS number represents exactly. These are weights and heights, well
    // inside that range, but parsing explicitly avoids a string reaching a
    // component that expects to do arithmetic on it.
    prePregnancyWeightKg: toNumber(row.pre_pregnancy_weight_kg),
    heightCm: toNumber(row.height_cm),
    marriage: {
      years: row.married_years,
      consanguinity: row.consanguinity === 'CONSANGUINEOUS' || row.consanguinity === 'NON_CONSANGUINEOUS'
        ? row.consanguinity
        : null,
    },
    conceptionMode: row.conception_mode === 'NATURAL' || row.conception_mode === 'IVF' ? row.conception_mode : null,
    closure: {
      outcome: row.outcome,
      outcomeDate: row.outcome_date,
      closedAt: row.closed_at,
      closedBy: row.closed_by,
      note: row.closure_note,
    },
    birthPlan: (row.birth_plan as unknown as BirthPlan | null) ?? null,
    version: row.version,
    createdAt: row.created_at,
  }
}

function toNumber(value: number | string | null): number | null {
  if (value === null) return null
  const parsed = typeof value === 'number' ? value : Number(value)
  return Number.isFinite(parsed) ? parsed : null
}
